### ISSUE TITLE
Jpy in Multi-Thread Based Application

### ISSUE THREAD

**Issue by krishna-k-1** [bcdev/jpy#50]
HI Norman,

Please suggest us as we are facing few *Memory issues* with usage of **jpy** in our application.

###### Context
We are building an Mutli-Language(Script oriented), distributed and muti-threading application in Java and we need to run user **Python Scripts** from our application (Application also supports **R**, **Groovy**). 

One functionality flow in our application is that, 
1. any can user uploads a python script and intimate the application to publish his python script, the script is loaded and run by a thread and here we are using jpy to handle User Python Scripts related tasks. 
2. Now user can kill any thread (meaning, stop his running script) make modifications to it and reload the scripts to application and run them (basically with new threads)

what we have observed is, as user kills and publishes new threads, JVM memory is handled with out any hassle but since I have no way to cleanup the loaded modules and since user uses **memory extensive**  modules like **opencv** etc, the memory is summing up to an extent where eventually at some point in time  application is crashing with memory crunch.

Could you please suggest a right approach to use **jpy** in this context or is this rite use-case to use jpy?

Thanks in advance.

**Comment by bcdev** [comment]
You cannot call into a Pythjon interpreter from more than one Java 
thread because the Python interpreter itself is not mult-thread-save. 
 From the Python C_API (thus from Java), there is only limited control 
about Python's garbage collection. You could try to start and shutdown a 
new Python interpreter every time you run a script. If you don't need to 
call back into Java from Python, then other solutions might work better 
for you, e.g. http://jpype.sourceforge.net/  (however, the 
bi-directionality is jpy's strength).

Otherwise, why can't you simply use Java's scripting engine together 
with Jython?

If you don't need direct, in-process memory sharing, you could also 
simply execute the Python interpreter with a Java ProcessBuilder.

Regards
     Norman

Am 24.06.2015 um 08:52 schrieb Krishna Rangaiah. K:
>
> HI Norman,
>
> Please suggest us as we are facing few /Memory issues/ with usage of 
> *jpy* in our application.
>
>
>             Context
>
> We are building an Mutli-Language(Script oriented), distributed and 
> muti-threading application in Java and we need to run user *Python 
> Scripts* from our application (Application also supports *R*, *Groovy*).
>
> One functionality flow in our application is that,
> 1. any can user uploads a python script and intimate the application 
> to publish his python script, the script is loaded and run by a thread 
> and here we are using jpy to handle User Python Scripts related tasks.
> 2. Now user can kill any thread (meaning, stop his running script) 
> make modifications to it and reload the scripts to application and run 
> them (basically with new threads)
>
> what we have observed is, as user kills and publishes new threads, JVM 
> memory is handled with out any hassle but since I have no way to 
> cleanup the loaded modules and since user uses *memory extensive* 
> modules like *opencv* etc, the memory is summing up to an extent where 
> eventually at some point in time application is crashing with memory 
> crunch.
>
> Could you please suggest a right approach to use *jpy* in this context 
> or is this rite use-case to use jpy?
>
> Thanks in advance.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/bcdev/jpy/issues/50>.
>

-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Dipl. Ing. Norman Fomferra
Brockmann Consult GmbH
www.brockmann-consult.de
Max-Planck-Straße 2
D-21502 Geesthacht
Tel: +49 (0)4152 889 303
Fax: +49 (0)4152 889 333
Amtsgericht Geesthacht HRB 698
Geschäftsführer Dr. Carsten Brockmann
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Please help Brockmann Consult to respect the
environment by not printing this email.
